exports.permissions = {
    "ADMINISTRATOR": "Administrator",
    "VIEW_AUDIT_LOG": "View Audit Log",
    "VIEW_GUILD_INSIGHTS": "View Server Insights",
    "MANAGE_GUILD": "Manage Server",
    "MANAGE_ROLES": "Manage Roles",
    "MANAGE_CHANNELS": "Manage Channels",
    "KICK_MEMBERS": "Kick Members",
    "BAN_MEMBERS": "Ban Members",
    "CREATE_INSTANT_INVITE": "Create Invite",
    "CHANGE_NICKNAME": "Change Nickname",
    "MANAGE_NICKNAMES": "Manage Nicknames",
    "MANAGE_EMOJIS": "Manage Emojis",
    "MANAGE_WEBHOOKS": "Manage Webhooks",
    "VIEW_CHANNEL": "Read Text Channels & See Voice Channels",
    "SEND_MESSAGES": "Send Messages",
    "SEND_TTS_MESSAGES": "Send TTS Messages",
    "MANAGE_MESSAGES": "Manage Messages",
    "EMBED_LINKS": "Embed Links",
    "ATTACH_FILES": "Attach Files",
    "READ_MESSAGE_HISTORY": "Read Message History",
    "MENTION_EVERYONE": "Mention @everyone, @here, and All Roles",
    "USE_EXTERNAL_EMOJIS": "Use External Emojis",
    "ADD_REACTIONS": "Add Reactions",
    "CONNECT": "Connect",
    "SPEAK": "Speak",
    "STREAM": "Video",
    "MUTE_MEMBERS": "Mute Members",
    "DEAFEN_MEMBERS": "Deafen Members",
    "MOVE_MEMBERS": "Move Members",
    "USE_VAD": "Use Voice Activity",
    "PRIORITY_SPEAKER": "Priority Speaker"
}

exports.badgesEmotes = {
    "DISCORD_EMPLOYEE": "<:discordemployee:776633014502555678>",
    "PARTNERED_SERVER_OWNER": "<:partnerowner:776628269356417036>",
    "HYPESQUAD_EVENTS": "<:hypesquad:776630121985343499>",
    "BUGHUNTER_LEVEL_1": "<:bughunter1:776631999959531570>",
    "HOUSE_BRAVERY": "<:braveryhouse:776629630408327189>",
    "HOUSE_BRILLIANCE": "<:brilliancehouse:776629668848861255>",
    "HOUSE_BALANCE": "<:balancehouse:776629582950432820>",
    "EARLY_SUPPORTER": "<:earlysupporter:776627862597009408>",
    "TEAM_USER": "Team User", //Should never be encountered
    "SYSTEM": "System", // Should never be encountered 
    "BUGHUNTER_LEVEL_2": "<:bughunter2:776632040643624990>",
    "VERIFIED_BOT": "<:verifiedbot:776626551025958912>",
    "EARLY_VERIFIED_BOT_DEVELOPER": "<:verifieddev:776627149452083212>",
}